### ISSUE TITLE
Pull requests?

### ISSUE THREAD

**Issue by gaborcsardi** [hadley/rsmith#4]
Hi Hadley, interested in pull requests for rsmith? I am planning to use it as the engine of a simple blog site, and added a lot of changes in my fork. Most important ones:
- Plugins receive the 'rsmith' object and _all_ files at the same time. This is much more flexible, and is actually needed for some plugins, like collections.
- The file reader was rewritten and the contents is stored as a raw vector. This needs some cleanup, it is actually better to store binary files as raw, others as text, as we process the text often, and then need to convert between raw and char all the time.
- Fixes for the `rmarkdown` plugin, so that you can use it to generate a complete website with multiple pages.
- A bunch of new plugins, most of them straightforward, and resembles a metalsmith plugin:
  - `collections`.
  - `permalinks`.
  - `branch` for conditional execution.
  - `replace` and `replace_meta` to transform file and global metadata.
  - `inspect`, calls `browser()` when building the chain.
  - `excerpts` to extract the first paragraph from a HTML or a MarkDown file.

If you are interested in having these in rsmith, then I can make sure that they are polished and send them as pull requests. 

With all these plugins I can generate the website like this:

```
blog %>%
  use(branch("^posts/.*$") %>%
      use(excerpts()) %>%
      use(permalinks(pattern = "posts/:title"))) %>%
  use(collections(name = "post", pattern = "posts/.*\\.Rmd$")) %>%
  use(branch("^posts/") %>%
      use(replace("next-post" = cut_index_rmd,
                  "previous-post" = cut_index_rmd))) %>%
  use(replace_meta("collections" = post_index)) %>%
  use(whisker(pattern = "\\.Rmd$")) %>%
  use(rmarkdown()) %>%
  build()
```

This is pretty good I think. The only glitches are `cut_index_cmd` and `post_index`, which should be ideally handled by the plugins as well.

```
cut_index_rmd <- function(metadata) {
  metadata$`_path` <- metadata$`_path` %>%
    sub("/index\\.Rmd$", "", .) %>%
    sub("^posts/", "../", .)
  metadata
}
post_index <- function(collections) {
  for (i in seq_along(collections$post)) {
    collections$post[[i]]$`_path` <- collections$post[[i]]$`_path` %>%
      sub("/index\\.Rmd$", "", .)
  }
  collections
}
```

**Comment by hadley** [comment]
Cool. I'd definitely be happy to review pull requests (although it might take me a while to get to them)

**Comment by gaborcsardi** [comment]
All right. They'll come soon.
